spring:
  datasource:
    platform: postgres
    jndi-name: java:comp/env/jdbc/postgres_ecommerce
    type: javax.sql.DataSource
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    database: POSTGRESQL
    show-sql: false
    #Method org.postgresql.jdbc.PgConnection.createClob() is not yet implemented.
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

logging:
  level:
    org.springframework: warn
    br.com.gbvbahia.ecommerce: DEBUG
